/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const a_salesorder_Logic = require('./code/a_salesorder-logic');

class cAP_Sales_Orders_GE159533Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'A_SalesOrder', async (request) => {
            await a_salesorder_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    cAP_Sales_Orders_GE159533Srv
};